name: Auto Release ZIP

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release with ZIP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create ZIP file of all repository files
      - name: Create ZIP file
        run: |
          zip -r redm-script.zip .

      # Step 3: Publish Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: "Release ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: boss-buyer.zip
