name: Auto Release ZIP

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release with ZIP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create ZIP file of all repository files
      - name: Create ZIP file
        run: |
          zip -r boss-buyer.zip .

      # Step 3: Create GitHub Release and upload ZIP file
      - name: Create GitHub Release and upload ZIP file
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: boss-buyer.zip
